import { Deck, Orientation, SeatStatus } from '../types/types';

export const seatMap = [
  {
    deck: Deck.LOWER,
    seatSize: { width: 77, height: 35 },
    map: [
      {
        x: 80,
        y: 14,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '01 L',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80,
        y: 14 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '02 L',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80,
        y: 14 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '03 L',
        status: SeatStatus.FEMALE_ONLY,
      },
      {
        x: 80 + 77 * 1.1,
        y: 14,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '04 L',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 1.1,
        y: 14 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '05 L',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 1.1,
        y: 14 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '06 L',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 2.2,
        y: 14,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '07 L',
        status: SeatStatus.FEMALE_ONLY,
      },
      {
        x: 80 + 77 * 2.2,
        y: 14 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '08 L',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 2.2,
        y: 14 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '09 L',
        status: SeatStatus.FEMALE_ONLY,
      },
      {
        x: 80 + 77 * 3.3,
        y: 14,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '10 L',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 3.3,
        y: 14 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '11 L',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 3.3,
        y: 14 + 35 * 3.3,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '12 L',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 4.4,
        y: 14,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '13 L',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 4.4,
        y: 14 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '14 L',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 4.4,
        y: 14 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '15 L',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 530,
        y: 40,
        orientation: Orientation.VERTICAL,
        seatNumber: '16 L',
        status: SeatStatus.AVAILABLE,
      },
    ],
  },
  {
    deck: Deck.UPPER,
    seatSize: { width: 77, height: 35 },
    map: [
      {
        x: 80,
        y: 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '17 U',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80,
        y: 35 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '18 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80,
        y: 35 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '19 U',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 1.1,
        y: 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '20 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 1.1,
        y: 35 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '21 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 1.1,
        y: 35 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '22 U',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 2.2,
        y: 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '23 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 2.2,
        y: 35 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '24 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 2.2,
        y: 35 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '25 U',
        status: SeatStatus.FEMALE_ONLY,
      },
      {
        x: 80 + 77 * 3.3,
        y: 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '26 U',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 3.3,
        y: 35 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '27 U',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 3.3,
        y: 35 + 35 * 3.3,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '28 U',
        status: SeatStatus.UNAVAILABLE,
      },
      {
        x: 80 + 77 * 4.4,
        y: 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '29 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 4.4,
        y: 35 + 1.2 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '30 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 80 + 77 * 4.4,
        y: 35 + 3.3 * 35,
        orientation: Orientation.HORIZONTAL,
        seatNumber: '31 U',
        status: SeatStatus.AVAILABLE,
      },
      {
        x: 530,
        y: 80,
        orientation: Orientation.VERTICAL,
        seatNumber: '32 U',
        status: SeatStatus.UNAVAILABLE,
      },
    ],
  },
];
